#!/bin/bash
source $HOME/todo/.todorc
case $1 in 
	new)
		temp=$(cat $TODO_PATH/id.txt)
		ID="${temp:=1}"
		ID=$(($ID+1))
		echo $ID >$TODO_PATH/id.txt
		echo $ID $2 >> $TODO_PATH/todo.txt
		echo "task added sucessfuly";;
	list) 
	;;
	
	done)
		myarray=$(echo $2 | tr ',' ' ')
		for word in $myarray 
		do
		grep "\<$word\>" $TODO_PATH/todo.txt | sponge $TODO_PATH/done.txt
		sed "/\<$word\>/d" $TODO_PATH/todo.txt | sponge $TODO_PATH/todo.txt
		done	
		;;
esac

