#!/bin/bash
sudo mkdir -p $HOME/.todo
sudo chmod 777 $HOME/.todo
source $HOME/.todorc 2>$HOME/.todo/errors.txt


TODO_PATH="${TODO_PATH:=$HOME/.todo}"
add_task(){
	if [ -z "$1" ]
  	then
		echo bad insert;
		exit 0
	fi
	temp=$(cat $TODO_PATH/id.txt 2>>$HOME/.todo/errors.txt)
	ID="${temp:=0}"
	ID=$(($ID+1))
	echo $ID >$TODO_PATH/id.txt
	echo $ID $1 >> $TODO_PATH/todo.txt 
	echo "$1 added sucessfuly";
}

list_task(){
	case $1 in
		# Handle the case when the user adds both of the option -- done
		-a|--all)echo $(cat $TODO_PATH/todo.txt 2>>$HOME/.todo/errors.txt) ;;
		-d|--done)echo $(cat $TODO_PATH/done.txt 2>> $HOME/.todo/errors.txt);;
		"")echo $(cat $TODO_PATH/todo.txt 2>>$HOME/.todo/errors.txt)
			echo $(cat $TODO_PATH/done.txt 2>>$HOME/.todo/errors.txt);;
		*) echo bad insert ;;      
	esac
}

done_tasks(){
	id_list=$(echo $1 | tr ',' ' ')
	for word in $id_list
	do
		grep "^\<$word\>" $TODO_PATH/todo.txt >> $TODO_PATH/done.txt
		sed -i "/^\<$word\>/d" $TODO_PATH/todo.txt >>  $TODO_PATH/todo.txt					
	done
}

if [ $# -gt 2 ]; then
	echo bad insert 
else
	case $1 in 
	new)
		add_task $2;;
	list)
	       	list_task $2;;
	done)
		done_tasks $2 ;;
	*)
		echo bad insert;;
esac

fi

